export { default as appLoader } from './appLoader'
export { default as dashboardLoader } from './dashboardLoader'
export { default as walletsLoader } from './walletsLoader'
export { default as authLoader } from './authLoader'
export { default as walletLoader } from './walletLoader'
export { default as settingsLoader } from './settingsLoader'
export { default as reflectLoader } from './reflectLoader'
